services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/html/static
    networks:
      - net_app
    depends_on:
      - backend-ui
      - backend-api

  backend-ui:
    build: ./backend-ui
    container_name: app_ui
    restart: unless-stopped
    volumes:
      - ./backend-ui:/app
      - static_volume:/app/static
    networks:
      - net_app
      - app_api
    depends_on:
      backend-api: 
        condition: service_started


  backend-api:
    build: ./api
    container_name: api
    restart: unless-stopped
    volumes:
      - ./api:/app
    networks:
      - app_api
      - api_db
    depends_on:
      postgres_db:
        condition: service_healthy

  postgres_db:
    image: postgres:15-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - api_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  net_app:
  app_api:
  api_db:     

volumes:
  postgres_data:
  static_volume: 